#build
FROM node:20-alpine as build

WORKDIR /usr/src/intesis

ENV PATH /usr/src/intesis/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm ci

COPY . ./

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/src/intesis/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]