name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: nilliam/restaurant-waiter-webapp/waiter-webapp
        registry: docker.pkg.github.com
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile.production