name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: intesisdev/waiter-app
        registry: docker.pkg.github.com
        username: intesisdev
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile.production
        tags: latest